config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'posts/new'

  post 'posts/new'

  get 'posts/index'

  post 'posts/index'

  get 'home/index'

  get 'home/about'

  get 'home/contact'

  get 'users/new'

  get '/profile' => 'users#show'

  # get 'users/show' => 'users#view'

  get 'users/edit'

  get 'users/index'


  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'

  resources :users
  resources :posts

  
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user

	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	validates :username, uniqueness: true, presence: true, length: {maximum: 25}
	validates :email, uniqueness: true, presence: true, length: { maximum: 50 }
	validates :password, confirmation: true,presence: true, length: {minimum: 3 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@user = User.all
  	@post = Post.all
  end

  def new
  end

  def create
    puts "TROY>>>>>>>>> #{params.inspect}"
    puts "TROY>>>>>>>>> #{session[:user_id]}"
    @post = Post.create(
      :content => params[:content], 
      :user_id => session[:user_id]
    )
    redirect_to posts_path(@post)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	result = User.all.where(
      email: params[:email], password: params[:password]).first
    if result
      session[:user_id] = result.id
      flash[:notice] = "You have logged in!"
      redirect_to user_path result
    else
      flash[:notice] = "Invalid login/password. Please try again."
      redirect_to "/login"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have logged out."
    redirect_to users_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
    @user = User.create(user_params)
      if @user.save
        redirect_to user_path(@user)
      else
      redirect_to new_user_path
    end
  end

  # def profile
  #   @user = User.find_by(id: session[:user_id])
  # end

  def show
  		@user = User.find_by(id: session[:user_id])

  end 

  def edit
  	@user = User.find(params[:id])
  end

  def index
  	@users = User.all
  	@posts = Post.all

  end

  def update
    @user = User.find(params[:id])
    @user.update(params[:user])
      redirect_to @user
  end

# 'strong_paramaters', this allows the following fields to pass through the create() method.

  private

  def user_params
    params.require(:user).permit(:username, :fname, :email, :password, :bio)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<h1>About Throw</h1>
<p>
	Ever heard of us? Throw is the cumulative work of Troy Starwalt over a few days.
</p>
<p>
This app isn't like other apps. Throw just works sometimes. You never know when it will break, and you get a little frustrated when it does.
</p>
<p>
	Take a look around though. Create an account and attempt a Throw.
</p>
<p>Thanks, </p>
<p>Troy</p>

app/views/home/contact.html.erb
<h1>Contact</h1>
<p>This is where you would see an email form.</p>

app/views/home/index.html.erb
<div id="billboard-wrapper">
	<div id="rotating-item-wrapper">
		<img class="rotating-item" src="/desktopRS.jpg" alt="a person entering a building" width="980" height="347" />
		<img class="rotating-item" src="/treesRS.jpeg" alt="photo of building across from our office" width="980" height="347" />
		<img class="rotating-item" src="/streetRS.jpg" alt="building entrance with neon backlit walls" width="980" height="347" />
		<img class="rotating-item" src="/hardRS.jpg" alt="building lobby window reflections" width="980" height="347" />
	</div>
</div>

<div id="entry">
	<p>
		<h1>Welcome to T<span class="hcolor">h</span>row. Here you can make all of your <span><a href="https://youtu.be/JC6AzmXrNbU" class="dreams">dreams come true</a></span>.</h1>
	</p>
	<p>
		If you haven't yet, you should definitely sign up for T<span class="hcolor">h</span>row.
	</p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<script src="https://use.typekit.net/nzz4sfp.js"></script>
	<script>try{Typekit.load({ async: true });}catch(e){}</script>
  	<title>MicroBlog</title>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>
</head>
<body>
	<header>
	<div id="top_bar">
		<h1 id="main_header">T<span class="hcolor">h</span>row</h1>
	</div>
	</header>
		<div id="wrapper">
			<div id="content">	
			<div id="pattern" class="pattern">		
				<nav>
					<ul class="navigation" role="navigation">					
						<li><a href="/home/index" class="navlink">Home</a></li>
						<li><%= link_to 'Throw', posts_path, class: 'navlink' %></li>
						<li><a href="/users" class="navlink">See Other Users</a></li>
						<li><a href="/profile" class="navlink">Profile</a></li>
						<li><a href="/users/new" class="navlink">Sign Up</a></li>
						<li><a href="/login" class="navlink">Login</a></li>				
					</ul>	
				</nav>
			</div>
			<div></div>
				<hr>
				<article id="main_content">
				<p class="flash_notice">
					<% if flash[:notice] %>
	                <%= flash[:notice] %>
	                <% end %>
				</p>
				<%= yield %>
				</article>
				<footer>
					<div id="footer_content">
						<hr>
						<div id="logo_footer">
						<img src="/bottom_logo.png">
						</div>
						<div id="copyright">
							<span>&copy; Trox</span>
							<span>All Rights Reserved</span>
						</div>
						<div id="otherlinks">
							<ul id="footernav">
								<li><%= link_to 'About', home_about_path,  class: "otherlinksa" %></li>
								<li><%= link_to 'Contact', home_contact_path, class: 'otherlinksa' %></li>
								<li><%= link_to 'Logout', logout_path, class: 'otherlinksa' %></li>
							</ul>
						</div>
					</div>		
				</footer>
			</div>
		</div>	
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	</body>
</html>

app/views/posts/index.html.erb
<h1>List of Throws</h1>
<h3>Click on a user to see more info.</h3>
<p> <hv><%= link_to "Throw your own.", new_post_path, class: 'throwlink' %></hv>
<table>
	<div id="list_of_throws">
		<tr>
			<th>Throw</th>
			<th>User</th>
		</tr>
		<% Post.all.each do |post| %>
		<tr>
			<td><%= post.content %></td>
			<td><%= link_to post.user.username, user_path(post.user) %></td>
		<!-- "/users/#{post.user.id}" -->
	</tr>
		<% end %>
	</div>
</table>

app/views/posts/new.html.erb
<h1>T<span class="hcolor">h</span>row Something</h1>
<div>
<%= form_tag(posts_path, method: 'post') do %> 
  <p>
    <%= label_tag('content', '', class: 'font_throw') %>
    <br>
    <%= text_area_tag('content', '', class: 'throw_area') %>
  </p> 
  <p>
    <%= submit_tag('Throw', class: 'throw_submit_btn') %>
  </p>  
<% end %>

app/views/users/destroy.html.erb
Thanks.

app/views/users/edit.html.erb
<h4>Let's updated your account.</h4>
<%= form_for @user, method: :put do |f| %>
<p>
	<%= f.label :username %>
	<%= f.text_field :username %>
</p>
<p>
	<%= f.label :fname %>
	<%= f.text_field :fname %>
</p>
<p>
	<%= f.label :email %>
	<%= f.text_field :email %>
</p>
<p>
	<%= f.label :password %>
	<%= f.text_field :password %>
</p>
<p class="profile">
	<%= f.label :bio %>
	<%= f.text_area :bio %>
</p>
<%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>See all of our lovely Throw users.</h1>

<% @users.each do |user| %>
<p>Username:  <%= user.username %></p>
<p>Date Created:  <%= user.created_at %></p>
<p>Number of Throws:  <%= user.posts.count %></p>
<hr>
<% end %>

app/views/users/new.html.erb
<h2>Sign up</h2>
<div class="user_forms">
<%= form_for @user do |f| %>
<p>
	<%= f.label :username %>
	<%= f.text_field :username, class: "input_area" %>
</p>
<p>
	<%= f.label "First Name" %>
	<%= f.text_field :fname, class: "input_area" %>
</p>
<p>
	<%= f.label :email %>
	<%= f.text_field :email, class: "input_area" %>
</p>
<p>
	<%= f.label :password %>
	<%= f.text_field :password, class: "input_area" %>
</p>
<p class="profile">
	<%= f.label :bio %>
	<%= f.text_area :bio, class: "input_bio_area" %>
</p>
<%= f.submit "Create Account", class: "submit_btn" %>
<% end %>
</div>

app/views/users/profile.html.erb
<h1>If you are here, you probably clicked on the Profile link.</h1>

<% if @user %>
	<p>
		You are logged in! Hi <%= @user.fname %>
	</p>
<% else %>
	<p>
		Sorry I don't know who you are. Please <%= link_to '/login' %>.
	</p>
<% end %>

Bio: <%= @user.bio %>

<p>
<%= link_to("delete", user_path(@user.id), method: :delete)%>
</p>

<p>
	<%= link_to("edit", edit_user_path(@user.id)) %>
</p>

app/views/users/show.html.erb
<h1>Thanks for visiting.</h1>

<% if @user %>
	<p>
		You are logged in! Hi <%= @user.fname %>
	</p>

	<p>Bio: <%= @user.bio %></p>

<p>
<%= link_to("delete", user_path(@user.id), method: :delete)%>
</p>

<p>
	<%= link_to("edit", edit_user_path(@user.id)) %>
</p>
<% else %>
	<p>
		Sorry I don't know who you are. Please <%= link_to "login", sessions_new_path %>.
	</p>
<% end %>